version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: uniqueuser
      POSTGRES_PASSWORD: uniquepassword
      POSTGRES_DB: uniquedatabase
    ports:
      - "5432:5432"
